image: go1.3
git:
  path: github.com/vtolstov/svirtnet
env:
  - GOROOT=/usr/local/go
  - PATH=$PATH:$GOROOT/bin:$GOPATH/bin
script:
  - GOPATH=$(pwd)/third_party/ go build -a -x -o release/svirtnet
  - GOPATH=$(pwd)/third_party/ go test -cover -v
publish:
  github:
    branch: master
  script:
    - mkdir -p release/
    - GOPATH=$(pwd)/third_party/ go build -a -x -o release/svirtnet
  artifacts:
    - release/
  tag: git describe --tags --candidates 1
  token: 122511e7de5476e172bd2dd5f465607bb2e45ea1
  user: vtolstov
  repo: svirtnet
